wandb:
  project: atmaCup18

dataset:
  competition_dir: /kaggle/input/atmaCup#18_dataset
  train_fold_path: /kaggle/input/cv-split/train_folds.csv

xgboost:
  execution:
    exp_id: exp_002
    best_exp_id: exp_002
    seed: 46
  params:
    objective: reg:absoluteerror
    max_depth: 7
    colsample_bytree: 0.7
    reg_alpha: 0.1
    reg_lambda: 0.1
    subsample: 1.0
    tree_method: gpu_hist
    random_state: 46
    learning_rate: 0.025
    n_estimators: 40000 # TODO
