wandb:
  project: atmaCup18

dataset:
  competition_dir: /kaggle/input/atmaCup#18_dataset
  train_fold_path: /kaggle/input/cv-split/train_folds.csv

lightgbm:
  execution:
    exp_id: exp_010
    best_exp_id: exp_010
    seed: 46
  params:
    boosting_type: gbdt
    objective: regression_l1
    max_depth: 7
    colsample_bytree: 0.7
    reg_alpha: 0.1
    reg_lambda: 0.1
    subsample: 1.0
    min_child_samples: 20
    subsample_freq: 0
    random_state: 42
    learning_rate: 0.01
    n_estimators: 1000000
    verbosity: -1

cnn:
  execution:
    exp_id: exp_011
    best_exp_id: exp_011
    seed: 46
  optimizer:
    lr: 0.01
    # weight_decay: 0.001
  trainer:
    max_epoch: 20
    es_patience: 20
    loss_window: 100000
    device: cuda
    monitor: valid_MeanAbsoluteError
    direction: minimize

ensemble:
  execution:
    exp_id: ensemble_001
    best_exp_id: ensemble_001
    seed: 46
  weights:
    xgboost: 0.5
    cnn: 0.5
