CATEGORY_MAPPING = {
    "gearShifter": {
        "park": 0,
        "neutral": 1,
        "drive": 2,
        "reverse": 3,
    },
    "target_name": {
        "x_0": 0,
        "y_0": 1,
        "z_0": 2,
        "x_1": 3,
        "y_1": 4,
        "z_1": 5,
        "x_2": 6,
        "y_2": 7,
        "z_2": 8,
        "x_3": 9,
        "y_3": 10,
        "z_3": 11,
        "x_4": 12,
        "y_4": 13,
        "z_4": 14,
        "x_5": 15,
        "y_5": 16,
        "z_5": 17,
    },
    "xyz": {
        "x": 0,
        "y": 1,
        "z": 2,
    },
    "traffic_class": {
        "green": 0,
        "yellow": 1,
        "red": 2,
        "straight": 3,
        "left": 4,
        "right": 5,
        "empty": 6,
        "other": 7,
    },
}

TARGET_COLS = [
    "x_0",
    "y_0",
    "z_0",
    "x_1",
    "y_1",
    "z_1",
    "x_2",
    "y_2",
    "z_2",
    "x_3",
    "y_3",
    "z_3",
    "x_4",
    "y_4",
    "z_4",
    "x_5",
    "y_5",
    "z_5",
]
